apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: docs-pr
  title: Add Backstage Documentation
  description: Add Backstage metadata and documentation to an existing repository
  tags:
    - recommended
    - techdocs
    - mkdocs
spec:
  owner: infrastructure
  type: documentation

  parameters:
    - title: Fill in some steps
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: A description for the component
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.schibsted.io

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ../docs-template/template
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}
          type: service

    - id: fetchFolderStructure
      name: Adding document structure
      action: fetch:plain
      input:
        url: "URL HERE"
        targetPath: ${{Path}}
      

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        repoUrl: ${{ parameters.repoUrl }}
        title: "Add documentation"
        branchName: add-docs
        description: |
          Add documentation
  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        text: "Go to PR"
