apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: docs-pr
  title: Add Backstage Documentation To Existing Repository
  description: Add Backstage metadata and documentation to an existing repository
  tags:
    - recommended
    - techdocs
    - mkdocs
    - testing
spec:
  owner: infrastructure
  type: documentation

  parameters:
    - title: Fill in some steps
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: Unique name of the Description
          ui:autofocus: true
          ui:options:
            rows: 5
        # owner:
        #   title: Owner
        #   type: string
        #   description: Unique name of the owner
        #   ui:autofocus: true
        #   ui:options:
        #     rows: 5
          # ui:options:
          #   rows: 5
    - title: Choose repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
          # ui:options:
          #   rows: 5
            allowedHosts:
              - github.com
  


  steps:
    # - id: fetch
    #   name: Template Docs Skeleton
    #   action: fetch:template
    #   input:
    #     url: "https://github.com/KetilUstad/cdn.NORIT/blob/main/mystyle.css"
    #     targetPath: ./trocs
    #     values:
    #       name: ${{ parameters.name }}
    #       description: ${{ parameters.description }}
    #       destination: ${{ parameters.repoUrl | parseRepoUrl }}
    #       owner: ${{ parameters.owner }}
      
    - id: fetchFolderStructure
      name: Adding document structure
      action: fetch:plain
      input:
        url: "https://github.com/KetilUstad/cdn.NORIT/blob/main/"
        targetPath: ./docs

    #  - id: fetch-docs
    #    name: Fetch Docs
    #    action: fetch:plain
    #    input:
    #     url: https://github.com/backstage/community/tree/main/backstage-community-sessions
    #     targetPath: ./community

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Add documentation"
        branchName: add-docs
        description: Add documentation

  output:
    links:
      - url: ${{ steps.publish.output.remoteUrl }}
        text: "Go to PR"



        #local ip not locahost
        #schibsted incident ansvarlig vil de ha vc link
